name: lawgism
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  flutter_switch: ^0.3.0
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.1
  google_sign_in: ^5.0.1
  image_picker: ^0.7.3
  intl: ^0.17.0
  json_serializable: ^4.1.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  change_app_package_name: ^0.1.2
  freezed: ^0.14.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/justice_cover.jpg
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
